#!/bin/sh -e

op=$1 ; shift

test -z "$1" && echo "Usage: $0 command id" && exit 1

if [ "$op" = "command" ] ; then

	show_machine=0
	if [ $1 = '-M' ] ; then # FIXME --machine
		shift
		show_machine=1
	fi

	for host in $(cat /etc/ganeti.hosts) ; do

		prefix=''
		test $show_machine && prefix="$host: "
		#echo "# ssh $host $*"
		ssh root@$host $* | sed "s/^/$prefix/"

	done

elif [ "$op" = "copyfile" ] ; then

	my_hostname=$(hostname -s)
	for host in $(cat /etc/ganeti.hosts | grep -v $my_hostname) ; do
		rsync $1 root@$host:$1
	done

elif [ "$op" = "install" ] ; then # use as "install it" since needs install command and arg

	ln -sfv `pwd`/gnt-cluster /usr/local/bin/

else
	echo "UNKNOWN [$op] $*"
	exit 1
fi
